package ljun.show.model;

import ljun.show.model.base.BaseAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Auth extends BaseAuth<Auth> {
	public static final Auth dao = new Auth();
}
