package ljun.show.model;

import ljun.show.model.base.BasePo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Po extends BasePo<Po> {
	public static final Po dao = new Po();
}
