package ljun.show.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setPoId(java.lang.Integer poId) {
		set("po_id", poId);
	}

	public java.lang.Integer getPoId() {
		return get("po_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}

	public java.lang.String getScore() {
		return get("score");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}

	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}

	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}

	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}

	public java.util.Date getDeletedTime() {
		return get("deleted_time");
	}

}
